//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Main.rc
//
#define IDC_MYICON                      2
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_Main                        107
#define IDI_SMALL                       108
#define IDC_PRAMFRAME                   109
#define IDD_MainWnd                     129
#define IDD_MainWnd_EN                  129
#define IDC_InformationShow             1000
#define IDC_WORK_TYPE                   1000
#define IDC_OpenUsbPrinter              1000
#define IDC_AdapterList                 1001
#define IDC_CloseUsbPrint               1001
#define IDC_ClearShow                   1002
#define IDC_MASK                        1002
#define IDC_OutputInfor                 1002
#define IDC_InforShow                   1002
#define IDC_AboutBox                    1003
#define IDC_ClearInfor                  1004
#define IDC_AdapterInfor                1005
#define IDC_Printer                     1005
#define IDC_BeginPrinter                1005
#define IDC_SearchNetAdapter            1007
#define IDC_PrintData                   1007
#define IDC_TIMEOUT                     1008
#define IDC_TestCnt                     1008
#define IDC_DeviceList                  1009
#define IDC_TestInterval                1009
#define IDC_DbgOut                      1010
#define IDC_StopPrinter                 1010
#define IDC_VERIFY_BIT                  1011
#define IDC_CutPrinter                  1011
#define IDC_PrinterPortList             1012
#define IDC_ObjList                     1012
#define IDC_GetDevConfig                1013
#define IDC_SerialPortList              1013
#define IDC_SpiModeSel                  1013
#define IDC_SpiCfg_Mode                 1013
#define IDC_SEARCH                      1014
#define IDC_SpiFreq                     1014
#define IDC_SpiCfg_Clock                1014
#define IDC_ResetDevice                 1015
#define IDC_RefreshObjList              1015
#define IDC_SetDeviceConfig             1016
#define IDC_TxPktLenS                   1016
#define IDC_SpiBitOrder                 1016
#define IDC_SpiCfg_ByteBitOrder         1016
#define IDC_ObjStatusList               1017
#define IDC_SpiCsSel                    1017
#define IDC_SpiCfg_ChipIndex            1017
#define IDC_RestoreDefaultConfig        1018
#define IDC_TxPktLenE                   1018
#define IDC_SpiCsStatus                 1018
#define IDC_CaptureEndpN                1019
#define IDC_JtagTapState                1019
#define IDC_TxInterTime                 1020
#define IDC_SpiCfg_CS1Polarity          1020
#define IDC_SendRndData                 1021
#define IDC_SpiCfg_CS2Polarity          1021
#define IDC_SendSpecFile                1022
#define IDC_MODULE_IP                   1023
#define IDC_SendFilePath                1023
#define IDC_MODULE_PORT                 1024
#define IDC_BrowseTxFile                1024
#define IDC_DEST_IP                     1025
#define IDC_HandleSetEndp               1025
#define IDC_DEST_PORT                   1026
#define IDC_AutoSpecEndp                1026
#define IDC_DATA_BIT                    1027
#define IDC_OnlyRxSel                   1027
#define IDC_STOP_BIT                    1028
#define IDC_StartCompAtBytesSel         1028
#define IDC_SAVE_CONFIG2                1029
#define IDC_StartCompAtBytes            1029
#define IDC_SaveRxRawSel                1030
#define IDC_RxLogFilePath               1034
#define IDC_RealShow                    1036
#define IDC_BAUD                        1037
#define IDC_RealDataToFile              1037
#define IDC_CLEAR_BUFF                  1038
#define IDC_StartTest                   1038
#define IDC_StartRecv                   1038
#define IDC_CloseDevice                 1038
#define IDC_RELINK_TIMES                1039
#define IDC_BrowseRxFile                1039
#define IDC_RELINK_INFINITY             1040
#define IDC_FlashIdentify               1040
#define IDC_FlashErase                  1041
#define IDC_FlashRead                   1042
#define IDC_FlashWrite                  1043
#define IDC_FlashAddr                   1044
#define IDC_FlashStartAddr              1044
#define IDC_FlashStartAddr2             1045
#define IDC_FlashDataSize               1045
#define IDC_FlashData                   1046
#define IDC_FlashRWSpeedTest            1047
#define IDC_FuncType                    1048
#define IDC_TestFilePath                1049
#define IDC_SelectTestFile              1050
#define IDC_TestLen                     1051
#define IDC_WriteFormFile               1052
#define IDC_ReadToFile                  1053
#define IDC_SelectDelay                 1054
#define IDC_SpiCfg_ActiveDelay          1054
#define IDC_UndoSelectDelay             1055
#define IDC_SpiCfg_DelayDeactive        1055
#define IDC_EnableCS                    1056
#define IDC_EnableOpEndAutoCS           1057
#define IDC_AutoDeativeCS               1057
#define IDC_SpiOut                      1058
#define IDC_SpiIn                       1059
#define IDC_StopTest                    1060
#define IDC_StopRecv                    1060
#define IDC_UndoSelectDelay2            1060
#define IDC_SpiOutLen                   1060
#define IDC_UndoSelectDelay3            1061
#define IDC_SpiInLen                    1061
#define IDC_SpiCfg_OutInIntervalT       1062
#define IDC_SaveInfor                   1063
#define IDC_JtagOut                     1063
#define IDC_JtagOutFilePath             1064
#define IDC_JtagOutLen                  1065
#define IDC_JtagOutFileSel              1066
#define IDC_StatusShow                  1067
#define IDC_JtagOutBitLen               1067
#define IDC_BtmFrame                    1068
#define IDC_AddFirst                    1069
#define IDC_JtagInsBit                  1070
#define IDC_CompareFile                 1071
#define IDC_JtagState_Switch            1071
#define IDC_OpenDevice                  1072
#define IDC_CMD_InitSPI                 1073
#define IDC_CMD_SPICsCtrl               1074
#define IDC_CMD_SPIStream               1075
#define IDC_CMD_BulkSpiIn               1076
#define IDC_CMD_BulkSpiOut              1077
#define IDC_JTAG_StreamOut              1078
#define IDC_JtagFileOut_A2              1079
#define IDC_JtagFileOut_D2              1079
#define IDC_JtagFileOut_D3              1079
#define IDC_ReadDeviceID                1080
#define IDC_JtagInstExec                1081
#define IDC_JtagDR_Write                1082
#define IDC_Jtag_ByteWrite              1082
#define IDC_JtagDR_SwitchTest           1083
#define IDC_JtagInLen                   1084
#define IDC_JtagIn                      1085
#define IDC_Jtag_ByteRead               1086
#define IDC_JtaShiftgChannel            1087
#define IDC_JtatTapReset                1088
#define IDC_Jtag_BitRead                1088
#define IDC_JtagReadToFile              1089
#define IDC_JtagIfConfig                1090
#define IDC_JtagOutLenName              1091
#define IDC_JtagInit                    1092
#define IDC_JtagTapInit                 1092
#define IDC_Jtag_InitTarget             1092
#define IDC_Jtag_DnFile_Exam            1093
#define IDC_JtagClockRate               1094
#define IDC_DataTransFunc               1095
#define IDC_JtagSendFromFile            1096
#define IDC_JtagInLenName               1096
#define IDC_JtagRecvFromFile            1097
#define IDC_JtagOutLenName2             1097
#define IDC_JtagMode                    1098
#define IDC_JtagOutBit                  1098
#define IDC_JtagOutLenName3             1099
#define IDC_JtagOutBit2                 1100
#define IDC_JtagInBit                   1100
#define IDC_Jtag_BitWrite               1101
#define IDC_JtagInBitLen                1102
#define IDC_JtagTranType                1103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
